#! /usr/bin/env bash
# Info: http://data.norge.no/data/registerenheten-i-br%C3%B8nn%C3%B8ysund/enhetsregisteret
# Download: http://hotell.difi.no/download/brreg/enhetsregisteret?download
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${SOURCE_DIR}"

# Timestamping is turned off on the server, so we can't use it for wget
# Download if missing or --update-source
if [ ! -e 'enhetsregisteret.csv' ] || [ "x$1" = "x--update-source" ]; then
  wget -O enhetsregisteret.csv "http://hotell.difi.no/download/brreg/enhetsregisteret?download"
fi

if [ ! -e "./enhetsregisteret.list" ] || [ "x$1" = "x--update-list" ]; then
        cat ./enhetsregisteret.csv | ../../scraper/default_extract > ./enhetsregisteret.list
fi
cat ./enhetsregisteret.list

