#! /bin/bash
FOLDER="./downloads/URLTeamTorrentRelease2013July"

# TODO: Err if file exsists and has >x lines
echo -n "" > $FOLDER/dotno.lines

find "$FOLDER" -name '*.xz' | \
xargs -P 4 -L 1 -I {} sh -c \
"xzcat '{}' | grep -a -F '.no' | uconv --from-code UTF-8 --from-callback substitute --to-code UTF-8 --to-callback substitute > '{}.lines'"
