#! /usr/bin/env bash

rm -f tmp.list
touch tmp.list

#for D in $(find . -maxdepth 1 -type d); do
#  if [ "x$D" != "x." ]; then
#    $D/list_domains 2>/dev/null >> tmp.list
#  fi 
#done;

for LIST_SCRIPT in $(find . -type f -name 'list_domains'); do
  $LIST_SCRIPT 2>/dev/null >> tmp.list
done

rm -f combine.list

cat tmp.list | sort | uniq > tmp2.list

## Consider s-ing and er-ing all domains
## cat tmp2.list | sed -e 's/\.no$/s.no/' > combine.list
## cat tmp2.list | sed -e 's/\.no$/er.no/' >> combine.list

# Combine.list is not IDN-ed
cat tmp2.list >> combine.list

rm tmp*.list
