#! /usr/bin/env bash
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${SOURCE_DIR}"

LAST_DATA=$(ls ./data | cut -d. -f1 | sort | tail -1)

#    (if don't exsist)          OR   (if not newer than last data)                     OR (if update forced)
if [ ! -e "./domeneshop.list" ] || [ ! -n "$(find ./domeneshop.list -newermt $LAST_DATA  2>/dev/null)" ] || [ "x$1" = "x--update-list" ]; then
	cat data/* | ../../scraper/default_extract > ./domeneshop.list
fi

cat ./domeneshop.list
