#! /usr/bin/env bash
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${SOURCE_DIR}"
cat ./dynamic_regexp_dotno | sed -e "s/\${CAT_DOMAINS}/$(./get_norid_cat_domains | sed 's#\\#\\\\#g')/" \
-e '/CAT_DOMAINS=/d' > ./static_regexp_dotno
