#! /usr/bin/env bash

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Valid chars: 
# https://www.norid.no/en/domeneregistrering/idn/idn_nyetegn/
VCHAR_EX_DASH='[a-z0-9\x{C5}\x{C6}\x{D8}\x{E0}\x{E1}\x{E4}-\x{EA}\x{F1}-\x{F4}\x{F6}\x{F8}\x{FC}\x{10D}\x{111}\x{144}\x{14B}\x{161}\x{167}\x{17E}]'
CAT_DOMAINS=$(${SOURCE_DIR}/get_norid_cat_domains)

EXP_REGEXP=$(cat <<'EOF'
(
  (?:
    # $x er alle godkjente tegn utenom -
    # Normalt domene, min 2 tegn (ikke -) med 0-61 tegn (inkl -) i mellom
    $x(?:$x|-){0,61}$x 
    |
    # $y er alle kategoridomener omringet av (?:...)
    # 0-62 $x fulgt av 0-62 $x fulgt av $x fulgt av kategoridomene 
    (?:
      $x
      |
      $x(?:$x|-){0,61}$x
    )\.$y
  )
  \.no
)  
(?!$x)
EOF
)
# (?:$x|-){0,62}\.$y
REGEXP="$(echo "$EXP_REGEXP" | sed -e 's/#.*$//' -e 's/ //g' | tr -d '\n')"
#set -x
#echo $REGEXP 
perl -CSD -ne "\$x=qr/${VCHAR_EX_DASH}/i; \$y=qr/(?:${CAT_DOMAINS})/i; while(/${REGEXP}/gi) { print \$1,\"\\n\"; }"